package com.sentinel.synth;

import java.util.List;
import java.util.Map;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/** The scrape endpoint, plus the two controls the load tests drive it with. */
@RestController
public class ExporterController {

    private final SeriesGenerator generator;

    ExporterController(SeriesGenerator generator) {
        this.generator = generator;
    }

    /** What Prometheus scrapes. Advances every counter by the time since the last scrape. */
    @GetMapping(value = "/metrics", produces = MediaType.TEXT_PLAIN_VALUE)
    public String metrics() {
        return generator.scrape();
    }

    /**
     * Flips chains into or out of breach at runtime.
     *
     * <p>This is what makes measurement 2 (breach storm) and measurement 3 (alert collapse)
     * possible: the fleet is healthy, Prometheus has real history, and then 30% of it breaks at a
     * known instant that can be compared against the incident's {@code openedAt}.
     */
    @PostMapping("/breach")
    public Map<String, Object> breach(@RequestParam(defaultValue = "0.3") double fraction) {
        int breaching = generator.applyBreachFraction(fraction);
        return Map.of("fraction", fraction, "breachingServices", breaching, "totalServices", generator.serviceCount());
    }

    /** Back to healthy, counters intact — this is a state change, not a restart. */
    @PostMapping("/heal")
    public Map<String, Object> heal() {
        generator.applyBreachFraction(0.0);
        return Map.of("breachingServices", 0, "totalServices", generator.serviceCount());
    }

    /** Zeroes every counter and rebuilds the fleet. Prometheus will see a counter reset. */
    @PostMapping("/reset")
    public Map<String, Object> reset() {
        generator.reset();
        return Map.of("totalServices", generator.serviceCount());
    }

    @GetMapping("/status")
    public Map<String, Object> status() {
        return Map.of("totalServices", generator.serviceCount(), "services", generator.serviceNames());
    }

    /**
     * The topology as a YAML fragment for {@code sentinel.dependencies}.
     *
     * <p>Served rather than generated by a script so there is exactly one definition of the
     * synthetic graph. A script that reimplemented the naming scheme would drift from the exporter
     * the first time either changed, and the failure would look like correlation being broken.
     */
    @GetMapping(value = "/topology.yml", produces = MediaType.TEXT_PLAIN_VALUE)
    public String topologyYaml() {
        var out = new StringBuilder("sentinel:\n  dependencies:\n");
        for (Map.Entry<String, List<String>> entry : generator.topology().entrySet()) {
            out.append("    ")
                    .append(entry.getKey())
                    .append(": [")
                    .append(String.join(", ", entry.getValue()))
                    .append("]\n");
        }
        return out.toString();
    }

    @GetMapping("/topology.json")
    public Map<String, List<String>> topologyJson() {
        return generator.topology();
    }
}
